import localFont from "next/font/local";
import "./globals.css";
import { Appbar,Footer } from '@/components'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Appbar/>
        <main className="flex-grow max-w-screen-2xl  w-full h-full mx-auto">
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
